# Site Settings
locale: "en-US"
title: "Homepage"
title_separator: "-"
name: &name "Shangjian Yin"
description: &description "CS PhD @ UCR"
url: https://sjy8460.github.io
baseurl: ""
repository: "academicpages/academicpages.github.io"

# Navigation bar
nav:
  - title: "Homepage"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "Talks"
    url: /talks/
  - title: "CV"
    url: /files/CV_PhD.pdf

# Site Author
author:
  name: "Shangjian Yin (尹商鉴)"
  avatar: "profile_peo.png"
  bio: "CS PhD @ UCR"
  location: "California, United States"
  googlescholar: "https://scholar.google.com/citations?user=_K2ICQkAAAAJ"
  email: "sjy8460@163.com"
  github: "SJY8460"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

timezone: America/Los_Angeles
